### ISSUE TITLE
[BUG] wrong license on eth-rlp

### ISSUE THREAD

**Issue by step21** [conda/grayskull#182]
**Describe the bug**
Somehow license was BSD-3-Clause instead of MIT, and license path to some pandoc path which didn't work.

**To Reproduce**
create recipe with `grayskull pypi eth-rlp`

**Expected behavior**
Right license (from setup.py) for example

**Outputs**
licence path was .eggs/pypandoc-1.5-py3.7.egg/EGG-INFO/LICENSE

**Environment:**
 - grayskull --version = 0.7.3

**Comment by marcelotrevisani** [comment]
That was fixed in older version and it is still working fine, I believe

Thanks for reporting it :)

```yaml
{% set name = "eth-rlp" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth-rlp-{{ version }}.tar.gz
  sha256: f3263b548df718855d9a8dbd754473f383c0efc82914b0b849572ce3e06e71a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - eth-utils >=2.0.0,<3
    - hexbytes >=0.1.0,<1
    - rlp >=0.6.0,<4

test:
  imports:
    - eth_rlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-rlp
  summary: 'eth-rlp: RLP definitions for common Ethereum objects in Python'
  license: MIT
  license_file: LICENSE
```
