### ISSUE TITLE
[BUG] `tool.flit.scripts` is not extracted as entry_points

### ISSUE THREAD

**Issue by BastianZim** [conda/grayskull#269]
**Describe the bug**

This is not 100% confirmed but currently the assumption is that `[tool.flit.scripts]` in a _pyproject.toml_ file is the same as `entry_points`. This is not extracted.

**To Reproduce**
1. Run Grayskull on package using _pyproject.toml_.
2. No `entry_points` are created.

**Expected behavior**

`entry_points` are extracted correctly.

**Outputs**
If applicable, add the output to help explain your problem.

Can be tried with `yaqc-qtpy`.

**Additional context**

Ref about it being equal: https://gitter.im/conda-forge/conda-forge.github.io?at=6026b6e7063b6c68d55680a7
Sample package that has the new scripts: https://gitlab.com/yaq/yaqc-qtpy/-/blob/main/pyproject.toml#L33

**Comment by bollwyvl** [comment]
Maybe now that PEP 517 metadata is supported (and starting to be used by more than just flit) we can start looking at that as the intermediate representation?

https://flit.pypa.io/en/latest/pyproject_toml.html#scripts-section

```toml
[project.scripts]
flit = "flit:main"
```

at that point, supporting a legacy "pun" for the name wouldn't be that hard.

**Comment by BastianZim** [comment]
Yeah but we need to figure out what exactly the equivalent is because flit also has https://flit.pypa.io/en/latest/pyproject_toml.html#entry-points-sections

Maybe https://flit.pypa.io/en/latest/pyproject_toml.html#scripts-section is `scripts` from setup.py? In that case it can't be noarch.

**Comment by bollwyvl** [comment]
I was surprised too, but I think it's a convenience: further down it says
you _can't_ have console_scripts and gui_scripts in the entry points table

**Comment by dholth** [comment]
You could build the wheel or otherwise generate the metadata, and parse scripts out of entry_points.txt

**Comment by marcelotrevisani** [comment]
Should we close this? or is it still a problem? I am a bit confused here, sorry :lay

**Comment by BastianZim** [comment]
I think it's still a problem.

In short: Pyproject.toml flit uses `[tool.flit.scripts]` for entry_points.

This example: https://gitlab.com/yaq/yaqc-qtpy/-/blob/main/pyproject.toml#L42 is not converted into an `entry_points` but it should.

The confusion above came because I wasn't 100% sure if pyproject.toml`[tool.flit.scripts]` are the same as `entry_points` but I think they are.

**Comment by dholth** [comment]
You could have it do the build and take the entry points out of dist-info.

**Comment by marcelotrevisani** [comment]
> You could have it do the build and take the entry points out of dist-info.

the only problem is that, I would prefer to avoid in creating the whole build, because grayskull just start the build and stop it after it gets all the metadata, that is for setup.py and related. For pyproject.toml I am pretty much parsing the toml file as it is faster and simple to do.

**Comment by marcelotrevisani** [comment]
With this PR I was able to generate the following recipe for ``yaqc-qtpy``
```bash
grayskull pypi yaqc-qtpy --strict-conda-forge
```

```yaml
{% set name = "yaqc-qtpy" %}
{% set version = "2022.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqc-qtpy-{{ version }}.tar.gz
  sha256: 6a6b73fb3179882bc46a18a1de9fc6c8ced2fffb8d0f5e00ed816a8d598a4ead

build:
  entry_points:
    - yaqc-qtpy = yaqc_qtpy.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - yaqc
    - yaq-traits
    - yaqd-control
    - click
    - qtpy
    - qtypes >=2022.6.0
    - pyqtgraph
    - pyside2
    - numpy
    - qtconsole

test:
  imports:
    - yaqc_qtpy
  commands:
    - pip check
    - yaqc-qtpy --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: Tooling for building simple yaq clients using qtpy.
  dev_url: https://github.com/yaq-project/yaqc-qtpy
  license: LGPL-3.0 AND CC0-1.0
  license_file:
    - LICENSE
    - yaqc_qtpy/splash-images/LICENSE
```
