### ISSUE TITLE
[BUG] Noarch is not found

### ISSUE THREAD

**Issue by BastianZim** [conda/grayskull#412]
**Describe the bug**

The following package should be noarch but Grayskull outputs it as arch: https://pypi.org/project/desert/#description

**To Reproduce**
1. `grayskull pypi --strict-conda-forge desert`

**Expected behavior**

Package is created as noarch

**Outputs**
If applicable, add the output to help explain your problem.

**Environment:**
 - conda list
 - pip list
 - grayskull --version

Version: 1.8.4

**Additional context**

Could it be because of the dataclasses?

The GitHub repo doesn't have the release which is why I linked the PyPI page.

**Comment by BastianZim** [comment]
Most probably a duplicate of https://github.com/conda-incubator/grayskull/issues/408

**Comment by BastianZim** [comment]
Have seen that also with the package `certbot`. It seems like Grayskull first determines if it can be noarch (It can't because it has a OS specific dependency) and then does the replacement of (In this example pywin32 to pywin32-on-windows) which allows it to become noarch.

**Comment by marcelotrevisani** [comment]
Indeed, I will need to check a few things related to the noarch. Thanks for reporting it!

**Comment by marcelotrevisani** [comment]
ok, got it
it didn't add the ``noarch: python`` because if you generate the package without ``--strict-conda-forge`` it is going to generate ``dataclasses  # [py<37]"``

**Comment by marcelotrevisani** [comment]
With this PR: #496 

I was able to generate the following recipe for ``desert``:

```bash
grayskull pypi desert --strict-conda-forge
```

```yaml
{% set name = "desert" %}
{% set version = "2022.9.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/desert-{{ version }}.tar.gz
  sha256: 0f45e098915e16452a269a1da0bcbbf31df0af2173899f1c097fb2e3b0265d89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - marshmallow >=3.0
    - attrs
    - typing_inspect
    - dataclasses

test:
  imports:
    - desert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-desert/desert
  summary: Deserialize to objects while staying DRY
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
```
