### ISSUE TITLE
[BUG] `grayskull` fails to recognise `poetry` entrypoints?

### ISSUE THREAD

**Issue by dhirschfeld** [conda/grayskull#477]
### Describe the bug
No entry point is defined for `py2puml` even though it is specified in the [`pyproject.toml`](https://github.com/lucsorel/py2puml/blob/175997a6b63b24e05689684305ae450b911eb023/pyproject.toml#L15-L16)
```toml
[tool.poetry.scripts]
py2puml = 'py2puml.cli:run
```

### To Reproduce
```
grayskull pypi py2puml
```

### Expected behavior
The recipe should have a `py2puml` entry point defined:
```yaml
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - py2puml = py2puml.cli:run
```

### Outputs
Actual result:
```yaml
{% set name = "py2puml" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py2puml-{{ version }}.tar.gz
  sha256: d655c5a5267677225d225297abde6df883d87551cb853426a502e2d4143609b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0

test:
  imports:
    - py2puml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lucsorel/py2puml
  summary: Generate PlantUML class diagrams to document your Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
```

### Environment:
```
❯ grayskull --version
2.3.0
```

**Comment by marcelotrevisani** [comment]
that is indeed missing, gonna put this on my backlog

**Comment by marcelotrevisani** [comment]
It is fixed with #489 

it generated the following recipe:

```yaml
{% set name = "py2puml" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py2puml-{{ version }}.tar.gz
  sha256: a6d126e9d964be9375f7837430b3f56320c5a33e067082d2a0b4fc071b710103

build:
  entry_points:
    - py2puml = py2puml.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0

test:
  imports:
    - py2puml
  commands:
    - pip check
    - py2puml --help
  requires:
    - pip

about:
  home: https://github.com/lucsorel/py2puml
  summary: Generate PlantUML class diagrams to document your Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
```
