### ISSUE TITLE
[BUG] Grayskull doesn't detect AGPL-3.0-or-later

### ISSUE THREAD

**Issue by pavelzw** [conda/grayskull#517]
**Describe the bug**

**To Reproduce**
```
grayskull pypi internetarchive
```

**Expected behavior**
`about.license` should be `AGPL-3.0-or-later`. Instead, it's `AGPL-3.0`. `AGPL-3.0` is deprecated, see https://spdx.org/licenses/AGPL-3.0

**Outputs**
```yml
[...]
about:
  home: https://github.com/jjjake/internetarchive
  summary: A Python interface to archive.org.
  license: AGPL-3.0
  license_file: LICENSE
[...]
```

**Environment:**
 - grayskull --version
```
2.5.1
```

**Additional context**
See https://github.com/jjjake/internetarchive/blob/6e2321652ab2bd13c517dabf5a6e01f420bca380/LICENSE#L637-L638 for the LICENSE file. This is flagged by the conda-forge-linting service: https://github.com/conda-forge/staged-recipes/pull/24886#issuecomment-1874039753
