### ISSUE TITLE
[BUG] `flit_core` not being mapped correctly to `flit-core`

### ISSUE THREAD

**Issue by dhirschfeld** [conda/grayskull#527]
When using the generator in the Prefix discord channel `grayskull` creates a recipe for `sqlmermaid` with the below requirements:
```yaml
requirements:
  host:
    - python >=3.8
    - flit_core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=2.0.0
```
`sqlmermaid` does indeed depend on `flit_core`:
https://github.com/endremborza/sqlmermaid/blob/aed1925d5455e26049f61a9905488145635bfea7/pyproject.toml#L21

...but on `conda-forge` the package is called [`flit-core`](https://github.com/conda-forge/flit-feedstock/blob/81b8a6d75c6371de253e5289921fd4667833b750/recipe/meta.yaml#L23)
